// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXiOQf46_ra_XvxAymt-9rAQJ1zY77ykI',
    appId: '1:803830166797:web:0b2b8468962b0a167aac44',
    messagingSenderId: '803830166797',
    projectId: 'farm-fresh-20426',
    authDomain: 'farm-fresh-20426.firebaseapp.com',
    storageBucket: 'farm-fresh-20426.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlHJoqR10_w3Z_LZC8vV8mppjJuJAkc-U',
    appId: '1:803830166797:android:176fe01680cee7557aac44',
    messagingSenderId: '803830166797',
    projectId: 'farm-fresh-20426',
    storageBucket: 'farm-fresh-20426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxjPR0HkeT3fp9IsysYZNXJHYdfzQA2w',
    appId: '1:803830166797:ios:3cd33b9dc13ee48c7aac44',
    messagingSenderId: '803830166797',
    projectId: 'farm-fresh-20426',
    storageBucket: 'farm-fresh-20426.appspot.com',
    androidClientId: '803830166797-ib6kv3kh182rrt049llf0hhki1f86s8v.apps.googleusercontent.com',
    iosClientId: '803830166797-7cn805m2vmv13vvn6naideeb639lqiuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmFresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArxjPR0HkeT3fp9IsysYZNXJHYdfzQA2w',
    appId: '1:803830166797:ios:3cd33b9dc13ee48c7aac44',
    messagingSenderId: '803830166797',
    projectId: 'farm-fresh-20426',
    storageBucket: 'farm-fresh-20426.appspot.com',
    androidClientId: '803830166797-ib6kv3kh182rrt049llf0hhki1f86s8v.apps.googleusercontent.com',
    iosClientId: '803830166797-7cn805m2vmv13vvn6naideeb639lqiuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXiOQf46_ra_XvxAymt-9rAQJ1zY77ykI',
    appId: '1:803830166797:web:deffbbd0352529d27aac44',
    messagingSenderId: '803830166797',
    projectId: 'farm-fresh-20426',
    authDomain: 'farm-fresh-20426.firebaseapp.com',
    storageBucket: 'farm-fresh-20426.appspot.com',
  );
}
